# Generated by Django 3.0.3 on 2020-04-01 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Izdavaci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=45, verbose_name='ime')),
                ('racun', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='racun')),
                ('email', models.EmailField(blank=True, default=None, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knjige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=30, verbose_name='naslov')),
                ('strana', models.IntegerField(blank=True, default=None, null=True, verbose_name='strana')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='cena')),
                ('opis', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='opis')),
                ('godinaIzdanja', models.IntegerField(default=2020, verbose_name='godinaIzdanja')),
                ('ISBN', models.CharField(max_length=28, unique=True, verbose_name='ISBN')),
                ('slika', models.ImageField(blank=True, default=None, null=True, upload_to=None)),
                ('kategorija', models.CharField(choices=[], default='', max_length=30, verbose_name='kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulicaIBroj', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='ulicaIBroj')),
                ('brojPoste', models.IntegerField(blank=True, null=True, verbose_name='brojPoste')),
                ('grad', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='grad')),
                ('telefon', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='telefon')),
                ('is_korisnik', models.BooleanField(default=False, verbose_name='korisnikstatus')),
                ('is_autor', models.BooleanField(default=False, verbose_name='autorstatus')),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumNarucivanja', models.DateTimeField(auto_now_add=True, null=True, verbose_name='datumNarucivanja')),
                ('datumPrijema', models.DateTimeField(blank=True, default=None, null=True, verbose_name='datumPrijema')),
                ('placeno', models.BooleanField(blank=True, default=False, null=True, verbose_name='placeno')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik+', to='TaskRestAPI.Korisnici', verbose_name='korisnik')),
            ],
            options={
                'unique_together': {('id', 'korisnik')},
            },
        ),
        migrations.CreateModel(
            name='OceneKnjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(default=1, verbose_name='ocena')),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knjigaID+', to='TaskRestAPI.Knjige', verbose_name='knjiga')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik+', to='TaskRestAPI.Korisnici', verbose_name='korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='KomentariNaKnjigama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField(blank=True, default='', max_length=112, null=True, verbose_name='komentar')),
                ('odobren', models.BooleanField(blank=True, default=False, null=True, verbose_name='odobren')),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knjiga+', to='TaskRestAPI.Knjige', verbose_name='knjiga')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik+', to='TaskRestAPI.Korisnici', verbose_name='korisnik')),
            ],
        ),
        migrations.AddField(
            model_name='knjige',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor+', to='TaskRestAPI.Korisnici', verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='knjige',
            name='izdavac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izdavac+', to='TaskRestAPI.Izdavaci', verbose_name='izdavac'),
        ),
        migrations.CreateModel(
            name='StavkeNarudzbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=1, verbose_name='kolicina')),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knjiga+', to='TaskRestAPI.Knjige', verbose_name='knjiga')),
                ('narudzbina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narudzbina+', to='TaskRestAPI.Narudzbine', verbose_name='narudzbina')),
            ],
            options={
                'unique_together': {('narudzbina', 'knjiga')},
            },
        ),
    ]
