# Generated by Django 3.0.3 on 2020-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskRestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjige',
            name='slika',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/slike_proizvoda'),
        ),
    ]
