# Generated by Django 3.0.3 on 2020-06-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskRestAPI', '0002_auto_20200409_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtisciKorisnika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.CharField(default=None, max_length=50, verbose_name='komentar')),
                ('odobren', models.BooleanField(blank=True, default=False, null=True, verbose_name='odobren')),
                ('datum', models.DateTimeField(blank=True, default=None, null=True, verbose_name='datum')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik+', to='TaskRestAPI.Korisnici', verbose_name='korisnik')),
            ],
        ),
    ]
